---
- name: Install Apache (httpd)
  hosts: web-server
  become: true
  tasks:
    - name: install (nginx)
      yum: 
        name: nginx
        state: latest
    - name: Start apache server
      service: 
        name: nginx
        state: started
...

